name: lep
services:
  frontend:
    pull_policy: build
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:80"
    environment:
      FRONTEND_SERVER_NAME: "localhost"
      BACKEND_URL: "http://lep-backend-1:8080"
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
  backend:
    pull_policy: build
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
