name: lep
services:
  frontend:
    pull_policy: build
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8080:80"
    environment:
      FRONTEND_SERVER_NAME: "localhost"
      BACKEND_URL: "http://lep-backend-1:8080"
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
  backend:
    pull_policy: build
    build:
      context: .
      dockerfile: backend.Dockerfile
