spring:
  application:
    name: web-2024
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
ffmpeg:
  path-to-ffmpeg: "/usr/bin/ffmpeg"
logging:
  level:
    org.springframework.web: DEBUG
long-expose:
  blend-batch-size: 50